version: '3.2'

services:

  nginx:
    image: 192.168.1.145:5000/proxy:v0.2
    #command:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - middleware
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  middleware:
    driver: overlay
    attachable: true


